/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.interfaces;

import io.swagger.model.LoginInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-10-10T06:19:32.249Z")

@Api(value = "login_info", description = "the login_info API")
@RequestMapping()
public interface LoginInfoApi {

    @ApiOperation(value = "Add new login information", nickname = "addLoginInfo", notes = "", tags={ "login_info", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/login_info",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addLoginInfo(@ApiParam(value = "login info object that needs to be added to the store" ,required=true )  @Valid @RequestBody LoginInfo body);


    @ApiOperation(value = "Update an existing login information", nickname = "updateLoginInfo", notes = "", tags={ "login_info", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Login info not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/login_info",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateLoginInfo(@ApiParam(value = "Login info object that needs to be update" ,required=true )  @Valid @RequestBody LoginInfo body);

}
