/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.interfaces;

import io.swagger.model.Worker;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-10-10T06:19:32.249Z")

@Api(value = "workerByName", description = "the workerByName API")
@RequestMapping()
public interface WorkerByNameApi {

    @ApiOperation(value = "Find worker by name", nickname = "getWorkerByName", notes = "Returns a single member", response = Worker.class, tags={ "worker", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Worker.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "member not found") })
    @RequestMapping(value = "/workerByName/{name}",
        produces = {"application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Worker>> getWorkerByName(@ApiParam(value = "name of worker to return",required=true) @PathVariable("name") String name);

}
